import type { ToolMeta } from '../types';

const encryptedFaq = {
  q: 'Does it work with password-protected PDFs?',
  a: 'No. Encrypted PDFs cannot be decrypted in this browser-only tool. You will see a clear message instead of a broken file. Remove the password in the app that created the PDF first.',
};

export const pdfTools: ToolMeta[] = [
  {
    id: 'pdf-merge',
    name: 'Merge PDF',
    category: 'pdf',
    description: 'Combine several PDF files into one document, in any order.',
    about: 'Select two or more PDFs, drag them into the order you want and merge them into a single document. Pages are copied as-is (text stays selectable, no quality loss) using pdf-lib entirely in your browser.',
    supportedFormats: ['pdf'],
    icon: 'merge',
    component: 'pdf/merge',
    keywords: ['merge', 'combine', 'join', 'pdf', 'append'],
    popular: true,
    batch: true,
    faq: [
      { q: 'Is there a file limit?', a: 'There is no artificial limit. Practical limits depend on your device memory; merging a few hundred megabytes works on most desktops.' },
      encryptedFaq,
    ],
  },
  {
    id: 'pdf-split',
    name: 'Split PDF',
    category: 'pdf',
    description: 'Split a PDF into single pages, fixed chunks or custom page ranges.',
    about: 'Split one PDF into several files: one file per page, every N pages, or custom ranges such as "1-3, 4-8, 9". Multiple results are downloaded together as a ZIP archive.',
    supportedFormats: ['pdf'],
    icon: 'split',
    component: 'pdf/split',
    keywords: ['split', 'separate', 'divide', 'pages', 'range', 'pdf'],
    popular: true,
    faq: [encryptedFaq],
  },
  {
    id: 'pdf-extract-pages',
    name: 'Extract PDF Pages',
    category: 'pdf',
    description: 'Pick pages visually and save them as a new PDF — or delete them.',
    about: 'See thumbnails of every page, click to select the ones you need (or type a range) and save them as a new PDF. Switch to "remove" mode to delete the selected pages instead.',
    supportedFormats: ['pdf'],
    icon: 'pages',
    component: 'pdf/extract',
    keywords: ['extract', 'select pages', 'delete pages', 'remove pages', 'pdf', 'pages'],
    faq: [encryptedFaq],
  },
  {
    id: 'pdf-rotate',
    name: 'Rotate PDF',
    category: 'pdf',
    description: 'Rotate all or selected PDF pages by 90°, 180° or 270°.',
    about: 'Fix sideways scans: rotate individual pages or the whole document and save the corrected PDF. Rotation is stored in the page dictionary, so content is not re-rendered or degraded.',
    supportedFormats: ['pdf'],
    icon: 'rotate',
    component: 'pdf/rotate',
    keywords: ['rotate', 'turn', 'orientation', 'landscape', 'portrait', 'pdf'],
    faq: [encryptedFaq],
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    category: 'pdf',
    description: 'Render PDF pages to PNG or JPG images at the resolution you choose.',
    about: 'Convert every page — or a selected range — of a PDF into PNG or JPG images using Mozilla pdf.js. Pick the resolution (DPI) and download images individually or as a ZIP.',
    supportedFormats: ['pdf'],
    icon: 'image',
    component: 'pdf/toImages',
    keywords: ['pdf to jpg', 'pdf to png', 'render', 'export pages', 'pdf to image'],
    popular: true,
    faq: [
      { q: 'Does the output look exactly like the PDF?', a: 'pdf.js renders the vast majority of PDFs faithfully. Very unusual fonts or features (e.g. some XFA forms) may render differently.' },
      encryptedFaq,
    ],
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    category: 'pdf',
    description: 'Combine JPG, PNG, WebP and other images into a single PDF.',
    about: 'Put photos, scans or screenshots into one PDF. Reorder images, choose page size (fit to image, A4 or Letter), orientation and margins. JPG and PNG are embedded without re-encoding.',
    supportedFormats: ['png', 'jpg', 'jpeg', 'webp', 'gif', 'bmp', 'svg', 'avif'],
    icon: 'pdf',
    component: 'pdf/fromImages',
    keywords: ['jpg to pdf', 'png to pdf', 'image to pdf', 'photos to pdf', 'scan'],
    popular: true,
    batch: true,
  },
  {
    id: 'pdf-info',
    name: 'PDF Info',
    category: 'pdf',
    description: 'Page count, page sizes, PDF version and document metadata.',
    about: 'Inspect a PDF without opening a viewer: number of pages, page dimensions, PDF version, encryption status and metadata such as title, author, creator, producer and dates.',
    supportedFormats: ['pdf'],
    icon: 'info',
    component: 'pdf/info',
    keywords: ['pdf info', 'metadata', 'page count', 'pages', 'author', 'properties'],
  },
];
