import type { ToolMeta } from '../types.ts';

/** Raster/vector formats the browser can decode in an <img>/canvas. */
export const IMAGE_INPUT = ['png', 'jpg', 'jpeg', 'webp', 'gif', 'bmp', 'svg', 'ico', 'avif'];

const converter = (
  id: string,
  from: string,
  to: 'png' | 'jpeg' | 'webp',
  fromExt: string[],
  extra: Partial<ToolMeta> = {},
): ToolMeta => {
  const toLabel = { jpeg: 'JPG', png: 'PNG', webp: 'WebP' }[to];
  return {
    id,
    name: `${from} to ${toLabel}`,
    category: 'image',
    description: `Convert ${from} images to ${toLabel} in your browser — batch supported, no upload.`,
    about: `Turn ${from} files into ${toLabel} images locally on your device. Select one or many files, adjust quality, and download the results one by one or all together as a ZIP archive.`,
    supportedFormats: fromExt,
    icon: 'convert',
    component: 'image/converter',
    preset: { to, from: fromExt },
    keywords: [from.toLowerCase(), toLabel.toLowerCase(), 'convert', 'converter', `${from} to ${toLabel}`.toLowerCase()],
    variantOf: 'image-converter',
    batch: true,
    title: `${from} to ${toLabel} Converter — Free, Private, Offline`,
    ...extra,
  };
};

export const imageTools: ToolMeta[] = [
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    category: 'image',
    description: 'Shrink JPG, PNG and WebP files with a quality slider and before/after preview.',
    about:
      'Reduce image file size directly in your browser. JPG and WebP are re-encoded at the quality you choose; PNG is optimised with colour quantisation (lossy, like TinyPNG) or kept lossless. Compare before and after, see the exact size saving and process whole batches at once.',
    supportedFormats: ['png', 'jpg', 'jpeg', 'webp'],
    icon: 'compress',
    component: 'image/compressor',
    keywords: ['compress', 'optimize', 'reduce size', 'smaller', 'tinypng', 'jpg', 'png', 'webp', 'quality'],
    popular: true,
    batch: true,
    faq: [
      { q: 'How much smaller will my images get?', a: 'It depends on the image. Photos saved as JPG or WebP at 70–80 % quality are usually 40–80 % smaller with little visible difference. The exact before/after size is shown for every file.' },
      { q: 'Can the result be larger than the original?', a: 'Yes, if the original is already well optimised. In that case the tool tells you, and you can keep the original.' },
      { q: 'Is EXIF metadata kept?', a: 'No. Images are re-encoded through a canvas, which does not copy EXIF/XMP metadata into the new file. GPS location and camera data are therefore not present in the output.' },
    ],
  },
  {
    id: 'compress-jpg', name: 'Compress JPG', category: 'image', variantOf: 'image-compressor', batch: true,
    description: 'Reduce JPG/JPEG file size locally with an adjustable quality slider.',
    supportedFormats: ['jpg', 'jpeg'], icon: 'compress', component: 'image/compressor', preset: { format: 'jpeg' },
    keywords: ['jpg', 'jpeg', 'compress', 'photo'],
  },
  {
    id: 'compress-png', name: 'Compress PNG', category: 'image', variantOf: 'image-compressor', batch: true,
    description: 'Make PNG files smaller with colour quantisation, right in your browser.',
    supportedFormats: ['png'], icon: 'compress', component: 'image/compressor', preset: { format: 'png' },
    keywords: ['png', 'compress', 'tinypng', 'quantize'],
  },
  {
    id: 'compress-webp', name: 'Compress WebP', category: 'image', variantOf: 'image-compressor', batch: true,
    description: 'Re-encode images as smaller WebP files with a quality slider.',
    supportedFormats: ['png', 'jpg', 'jpeg', 'webp'], icon: 'compress', component: 'image/compressor', preset: { format: 'webp' },
    keywords: ['webp', 'compress'],
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    category: 'image',
    description: 'Convert between PNG, JPG and WebP. Also reads BMP, GIF, SVG, ICO and AVIF.',
    about:
      'Convert images between the most common web formats without uploading them. Input: PNG, JPG, WebP, BMP, GIF (first frame), SVG, ICO and AVIF (when your browser supports it). Output: PNG, JPG or WebP. Transparent areas can be filled with a background colour when exporting to JPG.',
    supportedFormats: IMAGE_INPUT,
    icon: 'convert',
    component: 'image/converter',
    keywords: ['convert', 'png', 'jpg', 'jpeg', 'webp', 'bmp', 'svg', 'gif', 'ico', 'format'],
    popular: true,
    batch: true,
    faq: [
      { q: 'Which browsers can export WebP?', a: 'Chrome, Edge, Firefox and other Chromium browsers encode WebP natively. Safari cannot, so the tool automatically falls back to a bundled WebAssembly WebP encoder that runs locally.' },
      { q: 'What happens to animated GIFs?', a: 'Only the first frame is converted. Animation is not preserved because PNG, JPG and WebP output from a canvas is a still image.' },
      { q: 'What happens to transparency when converting to JPG?', a: 'JPG has no alpha channel, so transparent pixels are filled with the background colour you pick (white by default).' },
    ],
  },
  converter('png-to-jpg', 'PNG', 'jpeg', ['png']),
  converter('jpg-to-png', 'JPG', 'png', ['jpg', 'jpeg']),
  converter('jpg-to-webp', 'JPG', 'webp', ['jpg', 'jpeg'], { popular: true }),
  converter('png-to-webp', 'PNG', 'webp', ['png'], { popular: true }),
  converter('webp-to-png', 'WebP', 'png', ['webp']),
  converter('webp-to-jpg', 'WebP', 'jpeg', ['webp']),
  converter('bmp-to-png', 'BMP', 'png', ['bmp']),
  converter('svg-to-png', 'SVG', 'png', ['svg'], {
    about: 'Rasterise SVG vector graphics to PNG at any size. The SVG is rendered as an image by your browser (scripts inside the SVG are never executed), so you can pick the output width for crisp results.',
  }),
  converter('gif-to-png', 'GIF', 'png', ['gif']),
  converter('ico-to-png', 'ICO', 'png', ['ico']),
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    category: 'image',
    description: 'Resize images by pixels or percentage, keep aspect ratio, process batches.',
    about:
      'Change image dimensions precisely: set width and/or height in pixels with the aspect ratio locked, or scale by percentage. High-quality multi-step downscaling avoids jagged results. Resize dozens of images at once and download them as a ZIP.',
    supportedFormats: IMAGE_INPUT,
    icon: 'resize',
    component: 'image/resizer',
    keywords: ['resize', 'scale', 'dimensions', 'width', 'height', 'shrink', 'enlarge', 'percentage'],
    popular: true,
    batch: true,
    faq: [
      { q: 'Will the image lose quality?', a: 'Downscaling uses high-quality smoothing. Upscaling cannot add detail that is not there, so large enlargements will look soft.' },
      { q: 'Can I resize many images at once?', a: 'Yes. Select several files; the same size settings are applied to all of them and you can download everything as a ZIP.' },
    ],
  },
  {
    id: 'webp-resizer', name: 'Resize WebP', category: 'image', variantOf: 'image-resizer', batch: true,
    description: 'Resize WebP images (or resize anything and save as WebP).',
    supportedFormats: IMAGE_INPUT, icon: 'resize', component: 'image/resizer', preset: { format: 'webp' },
    keywords: ['webp', 'resize'],
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    category: 'image',
    description: 'Crop images freely or to 1:1, 4:3, 16:9, 9:16 and custom ratios.',
    about: 'Drag to select the area you want to keep, use a preset aspect ratio or type a custom one, and fine-tune with exact pixel values. Works with mouse, touch and keyboard.',
    supportedFormats: IMAGE_INPUT,
    icon: 'crop',
    component: 'image/cropper',
    keywords: ['crop', 'cut', 'trim', 'aspect ratio', 'square', 'instagram', '16:9', '1:1'],
    popular: true,
  },
  {
    id: 'image-rotator',
    name: 'Rotate & Flip Image',
    category: 'image',
    description: 'Rotate images 90°, 180°, 270° and flip horizontally or vertically.',
    about: 'Rotate and mirror one or many images losslessly in terms of dimensions. JPG output is re-encoded at the quality you choose; PNG stays lossless.',
    supportedFormats: IMAGE_INPUT,
    icon: 'rotate',
    component: 'image/rotator',
    keywords: ['rotate', 'flip', 'mirror', 'turn', '90', '180', '270'],
    batch: true,
  },
  {
    id: 'image-metadata',
    name: 'Image Metadata Viewer',
    category: 'image',
    description: 'See dimensions, format, size and EXIF data (camera, GPS, dates).',
    about: 'Inspect the technical details of an image: width, height, detected format, MIME type, file size, and every EXIF, IPTC and XMP field that can be read in the browser — including GPS coordinates when present.',
    supportedFormats: IMAGE_INPUT,
    icon: 'info',
    component: 'image/metadata',
    keywords: ['exif', 'metadata', 'gps', 'camera', 'info', 'dimensions', 'xmp'],
    faq: [
      { q: 'Why is there no EXIF data for my image?', a: 'PNG, GIF, BMP and SVG files rarely contain EXIF. Many apps and messengers also strip metadata when sharing. If the file has none, the tool says so instead of inventing values.' },
      { q: 'How do I remove EXIF?', a: 'Convert or compress the image with this site: canvas re-encoding never copies EXIF into the output. Note that this re-encodes the pixels (JPG/WebP are lossy).' },
    ],
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    category: 'image',
    description: 'Create favicon.ico, PNG icons in every size and the HTML snippet.',
    about: 'Upload a square logo (PNG, JPG, SVG, WebP) and get a multi-size favicon.ico (16, 32, 48 px), PNG icons from 16 to 512 px, an Apple touch icon, a web manifest and the ready-to-paste HTML snippet — all generated locally and bundled in a ZIP.',
    supportedFormats: ['png', 'jpg', 'jpeg', 'webp', 'svg', 'gif', 'bmp', 'ico'],
    icon: 'star',
    component: 'image/favicon',
    keywords: ['favicon', 'ico', 'icon', 'apple touch icon', 'manifest', 'website icon'],
    popular: true,
    faq: [
      { q: 'What image works best?', a: 'A square image of at least 512×512 px, ideally SVG or PNG with transparency. Non-square images are centred and padded.' },
      { q: 'Which ICO format is produced?', a: 'A standard ICO container with PNG-compressed 16, 32 and 48 px images, supported by all current browsers and Windows Vista and newer.' },
    ],
  },
];
